### ISSUE TITLE
continueforth.S is an empty file

### ISSUE THREAD

**Issue by omarandlorraine** [qgcarver/ContinueForth#1]
It looks as though this file is meant to contain the assembly listing (as evidenced by makefile and build.sh)

but as far as I can see, this file is empty. Am I missing something?

**Comment by qgcarver** [comment]
This project is a WIP on my machine.

`continueforth.S` not empty on my machine, but this project works pretty differently now, so I won't be using it.

I'm doing something like [PlanckForth](https://github.com/nineties/planckforth) instead of asm as a bootstrap mechanism (although a straightforward copy assembler will be a trivial Forth program within cf system.) where you hand-write an elf binary.

This [video series](https://youtu.be/XH6jDiKxod8) has a pretty good overview of how to do it, and naturally it turns out he has a similar ambition with bootstrapping a Forth system, as evidenced by his other content.

It's worth noting this is a for-funsies project as it stands, and I haven't pushed my work yet.

**Comment by qgcarver** [comment]
Seems prudent to create a readme to mention this since apparently somehow people are happening upon this page, (who knows how.)

**Comment by qgcarver** [comment]
yeah, ok readme's updated with up-to-date plans for the project
